version: "3.9"

services:

  web-service:
    container_name: nginx
    image: nginx:stable
    depends_on:
      - php-service
      - db-service
    working_dir: /var/www/html/
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-service:
    container_name: php-fpm81
    hostname: php-docker-service
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  db-service:
      container_name: postgres
      depends_on:
          - php-service
      image: postgres:14
      restart: always
      environment:
          DB_CONNECTION: pgsql
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: qwer1
          PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
          - ./database:/var/lib/postgresql/data
      ports:
          - 5432:5432

